import SectionHeader from './SectionHeader';
import Link from 'next/link';
export default function ServicePageSections({ title, description, icon, whatsappMessage }: { title:string; description:string; icon:string; whatsappMessage:string }) {
  const wa = `https://wa.me/916261031710?text=${encodeURIComponent(whatsappMessage)}`;
  return (<>
    <section className="py-20 bg-navy-950 text-center"><div className="max-w-4xl mx-auto px-4"><svg className="w-16 h-16 mx-auto mb-6 stroke-gold-400 fill-none" viewBox="0 0 24 24" strokeWidth="1"><path d={icon}/></svg><h1 className="text-4xl font-heading text-gradient mb-4">{title}</h1><p className="text-cream-100/60 mb-8">{description}</p><Link href={wa} target="_blank" className="bg-green-600 text-white px-8 py-4 rounded-xl font-bold">Enquire on WhatsApp</Link></div></section>
    <section className="py-16 bg-navy-900/30"><div className="max-w-7xl mx-auto px-4"><SectionHeader title="Why Choose Us?" /><div className="grid md:grid-cols-4 gap-6">{[{n:'Personalised',d:'Tailored to you.'},{n:'Expert',d:'25+ years.'},{n:'24×7',d:'Always available.'},{n:'Exclusive',d:'Best rates.'}].map((f,i)=><div key={i} className="glass-light rounded-xl p-4 text-center"><h4 className="text-gold-400 font-heading mb-1">{f.n}</h4><p className="text-cream-100/50 text-sm">{f.d}</p></div>)}</div></div></section>
    <section className="py-16 bg-navy-950"><div className="max-w-4xl mx-auto px-4"><SectionHeader title="How It Works" /><div className="grid md:grid-cols-3 gap-6">{[{s:'01',t:'Share',d:'Tell us your needs.'},{s:'02',t:'Plan',d:'Get a custom plan.'},{s:'03',t:'Book',d:'Confirm & travel.'}].map((st,i)=><div key={i} className="glass-light rounded-xl p-6 text-center"><span className="text-3xl font-heading text-gold-400">{st.s}</span><h3 className="text-gold-400 mt-2 mb-1">{st.t}</h3><p className="text-cream-100/50 text-sm">{st.d}</p></div>)}</div></div></section>
    <section className="py-12 bg-navy-900/50 border-y border-gold-400/5"><div className="max-w-5xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-6 text-center">{[{n:'25+',l:'Years'},{n:'50K+',l:'Clients'},{n:'100K+',l:'Tickets'},{n:'500+',l:'Tours'}].map((s,i)=><div key={i}><span className="text-3xl font-heading text-gradient block">{s.n}</span><span className="text-cream-100/40 text-sm">{s.l}</span></div>)}</div></section>
    <section className="py-16 bg-navy-950"><div className="max-w-4xl mx-auto px-4"><SectionHeader title="What Travellers Say" /><div className="grid md:grid-cols-3 gap-4">{[{q:"Flawless service!",n:"Ananya S.",c:"Mumbai"},{q:"Truly luxurious.",n:"Vikram R.",c:"Gwalior"},{q:"Highly recommended.",n:"Rakesh M.",c:"Delhi"}].map((r,i)=><div key={i} className="glass-light rounded-xl p-4"><p className="text-cream-100/70 italic text-sm mb-2">"{r.q}"</p><span className="text-gold-400 font-semibold text-sm">{r.n}</span><span className="text-cream-100/40 text-xs ml-2">{r.c}</span></div>)}</div></div></section>
    <section className="py-20 bg-gradient-to-br from-navy-900 to-navy-950 text-center"><div className="max-w-3xl mx-auto px-4"><SectionHeader title="Ready to Begin?" /><Link href={wa} target="_blank" className="bg-green-600 text-white px-8 py-4 rounded-xl font-bold text-lg">Start via WhatsApp</Link></div></section>
  </>);
}
